// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHgZPtfxsai4ACKZLrZ89Cg2bi8ilq3uY',
    appId: '1:111797288250:web:1417d8a5c2e4cd4b23a403',
    messagingSenderId: '111797288250',
    projectId: 'docsummarizer-7cb58',
    authDomain: 'docsummarizer-7cb58.firebaseapp.com',
    databaseURL: 'https://docsummarizer-7cb58-default-rtdb.firebaseio.com',
    storageBucket: 'docsummarizer-7cb58.appspot.com',
    measurementId: 'G-X5DXSD5P98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdYsWKxNI2QbZEFwpTq_Z51zZRtbj6Uo',
    appId: '1:111797288250:android:6d49b83fad6ba2f123a403',
    messagingSenderId: '111797288250',
    projectId: 'docsummarizer-7cb58',
    databaseURL: 'https://docsummarizer-7cb58-default-rtdb.firebaseio.com',
    storageBucket: 'docsummarizer-7cb58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlSjzVUscGrYjI3uiR9aP0nWcLatNfk1o',
    appId: '1:111797288250:ios:3200590ea0f4b23f23a403',
    messagingSenderId: '111797288250',
    projectId: 'docsummarizer-7cb58',
    databaseURL: 'https://docsummarizer-7cb58-default-rtdb.firebaseio.com',
    storageBucket: 'docsummarizer-7cb58.appspot.com',
    androidClientId: '111797288250-vklqhrbi24hjvth7upva9evq4aer3ejr.apps.googleusercontent.com',
    iosClientId: '111797288250-v8o6qtmk7s9plh227d52l02l3qvvplt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlSjzVUscGrYjI3uiR9aP0nWcLatNfk1o',
    appId: '1:111797288250:ios:3200590ea0f4b23f23a403',
    messagingSenderId: '111797288250',
    projectId: 'docsummarizer-7cb58',
    databaseURL: 'https://docsummarizer-7cb58-default-rtdb.firebaseio.com',
    storageBucket: 'docsummarizer-7cb58.appspot.com',
    androidClientId: '111797288250-vklqhrbi24hjvth7upva9evq4aer3ejr.apps.googleusercontent.com',
    iosClientId: '111797288250-v8o6qtmk7s9plh227d52l02l3qvvplt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHgZPtfxsai4ACKZLrZ89Cg2bi8ilq3uY',
    appId: '1:111797288250:web:e3810f45fa33e05f23a403',
    messagingSenderId: '111797288250',
    projectId: 'docsummarizer-7cb58',
    authDomain: 'docsummarizer-7cb58.firebaseapp.com',
    databaseURL: 'https://docsummarizer-7cb58-default-rtdb.firebaseio.com',
    storageBucket: 'docsummarizer-7cb58.appspot.com',
    measurementId: 'G-K2QJBEJP3M',
  );

}